runtime: python38

handlers:
- url: /$
  static_files: static/planner.html
  upload: static/planner.html

- url: /static/(.*\.(js|css))$
  static_files: static/\1
  upload: static/.*\.(js|css)$

- url: /.*
  script: auto
